language: julia

sudo: required

services:
  - docker

addons:
  apt:
    packages:
    - bar
    - moreutils

os:
  - linux

julia:
  - 0.4
  - 0.5
  - nightly

script:
  - mispipe "julia -e 'Pkg.clone(pwd()); Pkg.build(\"ValidatedNumerics\"); Pkg.test(\"ValidatedNumerics\", coverage=true)'" bar


matrix:
  allow_failures:
    - julia: nightly

notifications:
  email: false

after_success:
- julia -e 'cd(Pkg.dir("ValidatedNumerics")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder()); Codecov.submit(process_folder())'
